### ISSUE TITLE
bug in generation of DELETE action

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/staruml-cefact#104]
Please refer to the two attached models.  The only difference is that one has the DELETE action in every ```<<interface>>```

The one with the DELETE actions generates with errors.  
[VisaApplicationsModel.zip](https://github.com/gs-gs/staruml-cefact/files/4400433/VisaApplicationsModel.zip)

**Comment by faizanvahevaria** [comment]
@onthebreeze 
This issue is resolved so i am going to close this ticket
