### ISSUE TITLE
bug in naming expections

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/staruml-cefact#106]
Although it has been common practice so far to have the name of the ```<<interface>>``` as the plural of the class that is the source of the ```<<inerfaceREalisation>>```, there is nothing that requires this convention.  However the API generation fails to connect the interface to the class unless this naming convention is followed.

to repeat the bug

* create an interface called ```visa-applications``` and add a GET method
* create a class called ```application``` and add a couple of attributes.
* draw an interface realisation from application to visa-applications
* generate API

You'll see that the resource schema is empty.

If you rename the interface to ```applications``` (plural of the class) and try again it works.

this is a bug - there should be no dependency on singular/plural naming conventions - instead follow the ```<<interfacerealisation>>``` relationship.

**Comment by faizanvahevaria** [comment]
@onthebreeze Unable to reproduce the bug.

The generator doesn't have any binding to the name of the interface/class.

Package version: 0.3.5
and 
Package version: 0.3.9

Can you please tell me which version do you have?

**Comment by onthebreeze** [comment]
I was using 0.3.7 - reconfirmed several time - the bug exists in 0.3.7

Upgraded to 0.3.8 and the bug is gone.  So we can close the issue
