### ISSUE TITLE
Documentation of relationships not included in export

### ISSUE THREAD

**Issue by nissimsan** [gs-gs/staruml-cefact#107]
Documentation of relationships is not included in the export. This works fine for simple attributes, but not for (Composition) relationships. 

<img width="520" alt="image" src="https://user-images.githubusercontent.com/34443212/78133110-2c579680-741e-11ea-8925-023ccc75d362.png">

<img width="415" alt="image" src="https://user-images.githubusercontent.com/34443212/78133226-590bae00-741e-11ea-9402-d5d9b4bc82a8.png">

**Comment by nissimsan** [comment]
In the example included the documentation string "The consignee of this consignment." should have been included under consignee in the YAML.

**Comment by faizanvahevaria** [comment]
@nissimsan 
As you said i added 'description' field for the composition relationship in property.
consignee:
          $ref: '#/components/schemas/Consignee'
          description: 'The consignee of this consignment. '

Then i saw warning in swagger edito like : (Warning : Sibling values alongside $ref are ignored. To add properties to $ref, wrap $ref into allOf, or move extra properties into the reference definition)

so as warning says
I suggest it should be parsed like

consignee:
          allOf:
            - $ref: '#/components/schemas/Consignee'
            - description: 'Consignee. '

**Comment by nissimsan** [comment]
Hi @faizanvahevaria 

Hmm, you're right. This is a limitation to the spec which I was not aware of. 
https://github.com/OAI/OpenAPI-Specification/issues/1514

I agree with your suggestion of adding the class description, please progress with this suggestion.

Hopefully the OpenAPI spec will be fixed as some point, and then we can bring over relationship-description as well. 

Thank you Faizan!

**Comment by nissimsan** [comment]
Thanks @faizanvahevaria !
