### ISSUE TITLE
Please put attributes before associations when generating schema

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/staruml-cefact#112]
refs #109.  When I looked at the generated schema for /applicants, at first I thought all the attributes of applicant were missing because I saw nameTitle, familyName, and givenName (inherited from person) and then biographic and other related classes.  the actual attributes of applicant such as applicantId, resolvedPersonId, etc were there, but at the bottom of the schema. 

I think the right generation sequence should be

* attributes of parent generalisation first (eg attributes of person) - this is ok, current behaviour
* then attributes of the current class (this needs to change)
* then associations of the parent generalisation.
* then associations of the current class.

I know this doesn't make any difference technically - but the generated specs will be more readable.

**Comment by faizanvahevaria** [comment]
@onthebreeze the output JSON/YML is already in the sequence that you asked for.

I think you're looking at the HTML output on Swagger Editor (or Swagger Hub), and that is showing the output in different sequence.

So, I guess this is not something we can handle from our side. We can just raise a ticket in Swagger Editor or Swagger Hub.

**Comment by onthebreeze** [comment]
yes ok - closing this will worry about it seaprately
