### ISSUE TITLE
managing JSON core types - boolean, number and predefined formats not working

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/staruml-cefact#114]
refs #109 and #113 

I think we should simplify the who CEFACT types management and treat them no differently to any referenced type as described in #113.  

when a type is not linked to a referenced class then 

* check if the type name is the same as the standard [JSON core types](https://json-schema.org/draft-04/json-schema-core.html#rfc.section.3.5) (ie string, number, boolean) and use that primitive type.
* if not a primitive then check if the type name is any of the [predefined JSON string formats](https://json-schema.org/understanding-json-schema/reference/string.html#id8) (for now, really only date, time, date-time, email, and uri are important) and then apply that format syntax
* if none of the above, generate a warning (like you do now when you find a non-cefact type) and just make it "string"

**Comment by faizanvahevaria** [comment]
@onthebreeze 
We already are handling the primitive JSON types and also Date and DateTime in string format.
According to #76  and #77  , I've made the appropriate changes.

The warning message for String is shown because we are treating "Text" = "string"
If you set attribute type as "Text", then the output will be "string"

Your point about other JSON predefined string formats is valid.
And also my code should not be case sensitive for other types.

So, I'll
1. Remove case sensitive code for checking attribute type with JSON core types and predefined string formats
2. Add other JSON predefined string formats

I'll share a list of data type mapping with you in the next comment.

**Comment by onthebreeze** [comment]
ok so this is not working at all as requested.  We should NOT be treating Text as string.  and the error message "core types not defined" should not be appearing.  Please just forget all about CEFACT core types in your code logic.  

The logic should be:

* look at the type of an attribute.  If it is linked to a separate class in the UML model then follow it and generate accordingly.  as per the "linked-type-ok" image. this is working ok
* if there is no linked class then check if the type name matches a json schema primitive (eg boolean or string) or standard string pattern (eg date) and if so then generate the appropriate json schema.  This is NOT working - there are several "boolean" and "date" types in the model and the generator is making them all "string" - that is WRONG.
* if there is no linked type AND the names type is not a JSON primitive or standard string pattern THEN force it to "string" and write a warning.  An example of this is the various "code" types in the model.  there is no "code" class to which they are linked and "code" is not a json primitive.  ONLY this type of case should be forced to string and raise a warning.

**Comment by onthebreeze** [comment]
<img width="1440" alt="jsontype-ok" src="https://user-images.githubusercontent.com/13426392/79524264-68882980-80a3-11ea-8dc9-442950df492f.png">
<img width="1440" alt="nonjson-non-linked-warning" src="https://user-images.githubusercontent.com/13426392/79524274-6de57400-80a3-11ea-91e3-633e201068d7.png">
<img width="1440" alt="linkedtype-ok" src="https://user-images.githubusercontent.com/13426392/79524279-70e06480-80a3-11ea-97ba-197f52599a72.png">

**Comment by onthebreeze** [comment]
retested - seems ot be working.  thanks
