### ISSUE TITLE
POST operation for sub-resource is missing

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/staruml-cefact#146]
The source model has a POST operation on the ManifestLines sub-resource.  But the generated Open APi specification is missing the POST to the sub-resource.

![Sea Movements and Manifest Model ](https://user-images.githubusercontent.com/13426392/119255732-a9386780-bc00-11eb-88fc-d403c9f883ae.png)
![Swagger-Editor](https://user-images.githubusercontent.com/13426392/119255738-accbee80-bc00-11eb-8d7f-f749a4ac6940.png)

**Comment by kshychko** [comment]
There was two interface realisation in the model and one on the diagram. I added a check for a number of interface realistions per interface is one, otherwise the generation for subclasses is ignred.
