### ISSUE TITLE
ID attribute in interface should appear in generated API spec response schema

### ISSUE THREAD

**Issue by mrtnmrtn** [gs-gs/staruml-cefact#147]
We're using the the ID attribute specified in the interface as a key for some verbs e.g. GETs and PUTs, however the ID attribute does not currently appear in the POST response schema in the generated API spec.

Please add the ID specified in an interface (with the isID property) to the POST response message schema.

**Comment by kshychko** [comment]
@mrtnmrtn , I implemented the requested changes, please update the plugin and confirm if it is working for you as expected.

**Comment by mrtnmrtn** [comment]
Thanks for the quick update. It works well.
