### ISSUE TITLE
Code review feedback

### ISSUE THREAD

**Issue by patilgirish** [gs-gs/staruml-cefact#17]
- Add node_modules to gitignore
- Add a linter to the project, there are lot of inconsistencies in the code.
- Try catch statements are used everywhere ,  try-catch should only be used in portions of your code where you suspect errors will occur that are beyond your control, for whatever reasons.
I feel they could be avoided in lots of places

for example - found this function in `openApi-generator.js`, there are many issues with this code,
```
   getIndentString (options) {
     try{
        if (options.useTab) {
        return '\t'
        } else {
        var i
        var len
        var indent = []
        for (i = 0, len = options.indentSpaces; i < len; i++) {
            indent.push(' ')
        }
        return indent.join('')
        }
     }
     catch(error) {
          console.error("Found error",error.message);
          this.writeErrorToFile(error);
     }
    }

```

1. Indentations are completely wrong
2. try-catch is unnecessary, all you are doing is constructing the indent string using the options
3. options - could be a class property

You could simplify this function as below

```
  getIndentString() {
    return this.options.useTab
      ? "\t"
      : this.options.indentSpaces.map(() => " ").join("");
  }
```

**code-generator.js** 

- Duplicate code
- Lots of linting issues
- function arguments are already available in the class, no need to pass again. 

Please take a look at the refactored code below.

```
cons fs = require("fs");
const openApiGen = require("./openApi-generator");

class CodeGenerator {
  constructor(baseModel, basePath) {
    this.baseModel = baseModel;
    this.basePath = basePath;
    this.options = options;
  }

  getIndentString() {
    return this.options.useTab
      ? "\t"
      : this.options.indentSpaces.map(() => " ").join("");
  }

  generate(fileType) {
    try {
      fs.mkdirSync(this.basePath);
      const schemaWriter = new openApiGen.OpenApiGenerator();
      if (this.baseModel instanceof type.UMLPackage) {
        schemaWriter.generate(
          this.basePath,
          this.baseModel,
          this.options,
          fileType
        );
      } else {
        this.baseModel.ownedElements.forEach(element => {
          if (element instanceof type.UMLPackage) {
            schemaWriter.generate(
              this.basePath,
              element,
              this.options,
              fileType
            );
          }
        });
      }
    } catch (_e) {
      app.toast.error("Generation Failed!");
    }
  }
}

/**
 * Generate
 * @param {type.Model} baseModel
 * @param {string} basePath
 * @param {Object} options
 */
function generate(baseModel, basePath, options, fileType) {
  const codeGenerator = new CodeGenerator(baseModel, basePath, options);
  codeGenerator.generate(fileType);
}

exports.generate = generate;
```

**codegen-utils.js**

Try to handle indent and outdent within writeline function with an options argument

**Comment by arpentnoir** [comment]
- would it not have been simpler to construct a json object representing the spec and then serialise? seems unnecessary to hand roll yaml writer when js-yaml dump() would do this for you... 
- there are no tests. code could be restructured to be more testable. ultimately, you have a function which takes an .mdj file (presumably this is what starUML passes?) and returns an openAPI spec. you should then be able to make assertions on that spec object - should contain these paths, etc...

**Comment by onthebreeze** [comment]
@patilgirish and @arpentnoir - please review the changes based on your feedback - in the https://github.com/gs-gs/staruml-cefact/tree/json-first branch.
