### ISSUE TITLE
Generate json instead of yaml

### ISSUE THREAD

**Issue by Fak3** [gs-gs/staruml-cefact#2]
Right now the generator code is way more terrible than it should be because it tries to build plaintext yaml line-by-line with manual indent\dedent and hardcoded syntax constructs. It would be a lot more clean to generate json which we can convert to yaml any time later, manually or automatically using lib like https://www.npmjs.com/package/json2yaml

**Comment by kshychko** [comment]
@faizanvahevaria , the file is being generated with .json extension, by YAML content.

**Comment by onthebreeze** [comment]
Suggest that the extension allow the user to generate either YAML or JSON - but with a default of JSON.
