### ISSUE TITLE
generator does not follow generalisations across packages.

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/staruml-cefact#20]
Please refer to metamodel.mdj in https://github.com/edi3/edi3-model-interchange/tree/master/docs

"LibraryElement" is a class in "core" package and it is inherited by many classes in other packages.  But the generated schema does not include the library element $ref

**Comment by onthebreeze** [comment]
I dont think this is fixed

**Comment by faizanvahevaria** [comment]
@onthebreeze 
This ticket has already been resolved so please review and close this ticket from your end or i will close it from my side in next 2 days because this ticket is open for 6 months.

**Comment by faizanvahevaria** [comment]
@onthebreeze I am closing this ticket.

**Comment by faizanvahevaria** [comment]
@onthebreeze I am closing this ticket.
