### ISSUE TITLE
create single test

### ISSUE THREAD

**Issue by arpentnoir** [gs-gs/staruml-cefact#22]
```
As a reviewer of Pull Requests
I want to be able to determine that changes still produce valid openapi specifications
So that I can confidently and efficiently merge changes
```

without losing time on retrofitting unit tests,  I think we can improve things quite a bit with just one single test. 

```gherkin
Given an archetypal  starUML model X
When I pass X to some function which generates the openapi spec
Then the json object I get back should be a valid openapi spec
```

you can use this to validate the spec https://www.npmjs.com/package/openapi-schema-validator

once we have this we can improve the test by making assertions on relevant expectations we have about the content of the spec - should have these paths, etc... 

just being confident that the spec is valid is a good first step. 

as a pre-requisite to this task, we need an archetypal starUML model which demonstrates all of the features that we expect the tool to handle. 

once we have this archetype, we can begin to write expectations that can later be turned into more detailed tests. i.e. if an association in the starUML model has text matching this regex then I expect this to appear in the api spec, or whatever... the archetypal model and this list of expectations become the specification of how the tool should work

**Comment by onthebreeze** [comment]
yes, very good idea.

**Comment by faizanvahevaria** [comment]
@onthebreeze @arpentnoir 
Can you please share the StarUML mdj file that has all the features implemented that we expect the extension to handle?

**Comment by faizanvahevaria** [comment]
@arpentnoir 
You suggested using https://www.npmjs.com/package/openapi-schema-validator this to validate the Generated OpenAPI Spec JSON file.

But this one is not producing well descriptive errors.


I tried another one https://github.com/APIDevTools/openapi-schemas
This one just gives TRUE or FALSE.
Still not the ideal one to use.


Then I found https://github.com/APIDevTools/swagger-parser
This one looks perfect and providing detailed error messages.
I'll be using this package for validating the output OpenAPI Spec.

**Comment by faizanvahevaria** [comment]
We have already added following menus in our extension like...
Tools -> OpenAPI -> Test 'Package' or 'Diagra'
Tools -> OpenAPI -> Test Entire Package

 so please review and close this ticket from your end or i will close it from my side in next 2 days because this ticket has been open for a long time.

**Comment by faizanvahevaria** [comment]
@onthebreeze I am closing this ticket.
