### ISSUE TITLE
Specification still generates with bugs

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/staruml-cefact#24]
Using the attached mdj (identity package) and  using the latest generator in this repository, I generated the attached json, which when loaded to swagger hub gave 12 errors and 13 warnings.  https://app.swaggerhub.com/apis/onthebreeze/identity/1.0.0#/

* Why did the swagger errors not get reported at generation time?
* what is causing the errors?

The error handling is still far from satisfactory.  Lets give this more focus.
[Identity-API.zip](https://github.com/gs-gs/staruml-cefact/files/3469709/Identity-API.zip)

**Comment by faizanvahevaria** [comment]
This is bug is resolved so please review and close this ticket from your end or i will close it from my side in next 2 days because this ticket has been open for a long time.

**Comment by faizanvahevaria** [comment]
@onthebreeze I am closing this ticket.
