### ISSUE TITLE
camelCasing on exported attribute names 

### ISSUE THREAD

**Issue by nissimsan** [gs-gs/staruml-cefact#25]
Hi - fantastic tool! Much appreciated!
There's a convention that attribute names are camelCase'ed with a non-capital start letter. Wouldn't it make sense to ensure that such conventions are followed in the export? 
Nis

**Comment by faizanvahevaria** [comment]
Hello Nis,
We are not following any conventions while user export. We export attributes and classname same as  it is available in our model. So, I am closing this issue for now. 
Thanks.
