### ISSUE TITLE
Hangs on large models

### ISSUE THREAD

**Issue by nissimsan** [gs-gs/staruml-cefact#27]
Hi Faizan et al.,

When I run your plugin on a large model (one which has the full buy ship pay model), it hangs for a very long time, maxing out the processor. 

Let me know if you want a copy of the project file causing this. 

Nis

**Comment by faizanvahevaria** [comment]
@nissimsan Please share the model file so I can also check and debug it.

**Comment by faizanvahevaria** [comment]
Hello Nis,
This is issue is fixed in our next release. So, Please test when latest release availabe and let me know if any other query.
