### ISSUE TITLE
error when target of generalisation is in a different package

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/staruml-cefact#28]
to re-produce

* open model file and attempt generation from town plan meta-model
* error is generated per attached screenshot
<img width="1680" alt="Error message API generator" src="https://user-images.githubusercontent.com/13426392/64753411-79e5e200-d566-11e9-8ec8-c04df7a4ddb5.png">
[Metamodel.mdj.zip](https://github.com/gs-gs/staruml-cefact/files/3603673/Metamodel.mdj.zip)

**Comment by faizanvahevaria** [comment]
This bug is already resolved so please review and close this ticket from your end or i will close it from my side in next 2 days because this ticket has been open for a long time.

**Comment by faizanvahevaria** [comment]
@onthebreeze I am closing this ticket.
