### ISSUE TITLE
when referenced class has an "isID" that is inherited from a parent then the generator does not recognise it.

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/staruml-cefact#29]
using the same model as #28 - try to generate a schema for the domain metamodel.  the following error is generated.

<img width="1680" alt="IsIDErrorMessage" src="https://user-images.githubusercontent.com/13426392/64763890-474ae200-d584-11e9-9b0f-c9af683f5628.png">

however, the "isID" tag exists on a property of the parent "library element" class so it should be inherited by the "entity" class and therefore visible to the referencing "relationship" class.

**Comment by faizanvahevaria** [comment]
This error already been resolved so please review and close this ticket from your end or i will close it from my side in next 2 days because this ticket has been open for a long time.

**Comment by faizanvahevaria** [comment]
@onthebreeze I am closing this ticket.
