### ISSUE TITLE
Move ids properties to a separate schema

### ISSUE THREAD

**Issue by kshychko** [gs-gs/staruml-cefact#3]
For aggregation and relationship class relations it makes sense to move ids properties of the target class to a separate component schema so they can be re-used.

Please see the commit which reflects the proposed changes - https://github.com/edi3/edi3-uml-profile/commit/8aa6a3cd844f6856bf7a42ea01f688a719e59cc7

**Comment by faizanvahevaria** [comment]
@kshychko @onthebreeze 
Should we separate only  TransportParty( relationship class) schemas to TransportParty and TransportPartyIds Or All classes of diagram ?

**Comment by kshychko** [comment]
@faizanvahevaria I think this rule should be applied only to classes which are targets in aggregation or relationship class relations. Otherwise we end up with too many schema definitions, and in usual cases separation doesn't seem to be reasonable.

**Comment by faizanvahevaria** [comment]
@kshychko Please review this issue. If all good, then let's close this issue

**Comment by kshychko** [comment]
@faizanvahevaria looks good to me, except Components schemas alphabet order seems to be broken:
```
TransportPartyIds
TransportRouteIds
TransportMeans
TransportMeansParty
TransportMovement
TransportMeansIds
TransportMovementParty
TransportParty
TransportRoute
```
Can this be fixed?

**Comment by onthebreeze** [comment]
Probably best to follow the same order as in the UML model.  Designer might have some logic in putting ids at the top, grouping like items etc

**Comment by faizanvahevaria** [comment]
@kshychko I will try to fix alphabet order.
