### ISSUE TITLE
please get rid of short keys

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/staruml-cefact#31]
please see screenshot.  please get rid of the short cut keys for all the generator actions.  it exposes too much risk that the generator will be invoked by accident.

<img width="1680" alt="get rid of short cuts" src="https://user-images.githubusercontent.com/13426392/65382825-191d8d00-dd50-11e9-9d6a-6340d4bb7cfd.png">

**Comment by faizanvahevaria** [comment]
We have removed short cut keys in our next release 0.2.5. So, I am going to close this issue for now.
