### ISSUE TITLE
generating empty schema from package without definitions

### ISSUE THREAD

**Issue by Fak3** [gs-gs/staruml-cefact#40]
Plugin Version: current master

When i selected `TransportDomain` package to generate from, the plugin silently generated empty schema, as it does not have any schema definitions. It would be useful if the plugin displayed a warning in that case (perhaps easier to implement), or does not show packages without schema definitions, when asked to pick one from the list
```
{
    "openapi": "3.0.0",
    "info": {
        "description": "",
        "title": "TransportDomain",
        "version": ""
    },
    "servers": [],
    "paths": {},
    "components": {
        "schemas": {}
    }
}
```

**Comment by faizanvahevaria** [comment]
Hi,
You select TransportDomain package to generate OpenApi specs. There are no elements inside the 'TransportDomain'. We have to select the package which has the UML elements like class, interface, relationship.
But you are right we should alert user when package has no any elements.
