### ISSUE TITLE
Duplicated relationship with relationship class

### ISSUE THREAD

**Issue by Fak3** [gs-gs/staruml-cefact#41]
When Relationship Class is used to extend aggregation relationship, the generator outputs two properties - one simple, and one extended with Relationship Class. I believe that it should only produce one extended property. For example in the sample uml [file](https://edi3.org/specs/edi3-uml-profile/develop/SampleModel.mdj) `TransportMeans` has associated `TransportMeansParty`, which is extension of `TransportParty`. In the openapi schema, produced by generator `TransportMeans` has two properties - `TransportMeansParty` and `MeansParty`, while there should be only one - `TransportMeansParty`.
```
TransportMeans:
  properties:
      TransportMeansParty:
          items:
            allOf:
              - $ref: '#/components/schemas/TransportPartyIds'
              - $ref: '#/components/schemas/TransportMeansParty'
              - type: object
          type: array
      MeansParty:
          items:
            allOf:
              - $ref: '#/components/schemas/TransportPartyIds'
              - type: object
          type: array
```

**Comment by faizanvahevaria** [comment]
Hello 
You mean it should be like as below ?

TransportMeans:
  properties:
     MeansParty:
          items:
               allOf:
                    - $ref: '#/components/schemas/TransportPartyIds'
                    - $ref: '#/components/schemas/TransportMeansParty'
                    - type: object
          type: array

**Comment by Fak3** [comment]
Yes

**Comment by Fak3** [comment]
Actually please hold this until we decide on https://github.com/edi3/edi3-uml-profile/issues/8

**Comment by faizanvahevaria** [comment]
Okey

**Comment by Fak3** [comment]
Superseded by #56 
closing
