### ISSUE TITLE
Add support for example values

### ISSUE THREAD

**Issue by nissimsan** [gs-gs/staruml-cefact#44]
It'd be awesome to have a way to add example values for attributes into the UML and have them also exported into the generated openapi.

Here is an example of how examples look in the openapi spec: 
``` 
            "Consignment": {
                "type": "object",
                "properties": {
                    "bookingNumber": {
                        "description": "The unique identifier assigned by the carrier to this consignment when cargo space is reserved prior to loading.",
                        "type": "string",
                        "example": "969855342"
                    },
``` 

![image](https://user-images.githubusercontent.com/34443212/69326844-ce839880-0c4c-11ea-96b7-5f50c18273a9.png)

I haven't found any dedicated form in StarUML to fill this in, so I'm thinking it would have to somehow be added along with the "Documentation". Say, for example, after the documentation is provided, an example could be provided with some kind of new line + escape character. The above example could for example be specified in the Description field like this in "Documentation : 

<img width="324" alt="image" src="https://user-images.githubusercontent.com/34443212/69327363-b5c7b280-0c4d-11ea-8b54-c6732e52a40a.png">

**Comment by onthebreeze** [comment]
Suggest that we use the standard UML “default value” field to hold this example value - and update the openAPI generator to populate “example” from the uml “default value”

Also we should extend the interchange schema to include an “example” property

**Comment by faizanvahevaria** [comment]
Right now we do not have dedicated field to populate "example" from StarUML

**Comment by onthebreeze** [comment]
Use the “default value” field

**Comment by faizanvahevaria** [comment]
Mean, Write "example":"1234567890" in defaultValue field and populate in OpenAPI ?

**Comment by onthebreeze** [comment]
No I meant put the value “1234567890” in UML defaultValue field and populate the openAPI “example” field with the same value.  It’s just a field mapping - whenever you find something in UML defaultValue then you create an openAPI example field and put the same value there

**Comment by faizanvahevaria** [comment]
Okey

**Comment by nissimsan** [comment]
Good idea to use StarUML's defaultValue for this, @onthebreeze.  

@faizanvahevaria , the values come through correctly, but you map them to `default`. It should instead map to `example`. 

<img width="268" alt="image" src="https://user-images.githubusercontent.com/34443212/70161964-e9153300-168a-11ea-99d2-18564ec94134.png">

**Comment by faizanvahevaria** [comment]
@nissimsan 
Please check now

**Comment by faizanvahevaria** [comment]
@nissimsan 
Please close this issue if it is resolved

**Comment by faizanvahevaria** [comment]
@nissimsan 
This task is already been done so please review and close this ticket from your end or i will close it from my side in next 2 days because this ticket has been open for a long time.

**Comment by faizanvahevaria** [comment]
@onthebreeze I am closing this ticket.
