### ISSUE TITLE
Support for exporting date and date-time

### ISSUE THREAD

**Issue by nissimsan** [gs-gs/staruml-cefact#47]
When attributes are tagged as `DateTime`, it should get exported as 
```
  "dateOfIssue": {
    "type": "string",
    "format": "date-time"
  }
```
When attributes are tagged as `Date`, it should get exported as 
```
  "dateOfIssue": {
    "type": "string",
    "format": "date"
  }
```

In accordance with the openapi spec:  https://swagger.io/specification/#dataTypes

**Comment by nissimsan** [comment]
Great, thanks Faizan!

**Comment by faizanvahevaria** [comment]
> Great, thanks Faizan!

WC
