### ISSUE TITLE
Mandatory relationships no longer come out as mandatory

### ISSUE THREAD

**Issue by nissimsan** [gs-gs/staruml-cefact#51]
Mandatory relationships, defined as multiplicity: `1` is not tagged as mandatory on the exported api spec. 
Note that it does work for `1-*` work, just not for multiplicity `1`. 
I'm attaching a model and an api export. Look for example at the Consignment-Consignee relationship. 

[Bill Of Lading.txt](https://github.com/gs-gs/staruml-cefact/files/3905370/Bill.Of.Lading.txt)

[tl-docgen-model.txt](https://github.com/gs-gs/staruml-cefact/files/3905372/tl-docgen-model.txt)

**Comment by nissimsan** [comment]
Fabulous, good job @faizanvahevaria !

**Comment by faizanvahevaria** [comment]
Thanks @nissimsan
