### ISSUE TITLE
Support for JSON Schema

### ISSUE THREAD

**Issue by nissimsan** [gs-gs/staruml-cefact#52]
As discussed on slack, when choosing output format (JSON, YML or JSON+YML), it should also be possible to export "JSON Schema". 
What's different compared to what we have already is just:
- Don’t export the verbs/paths, but only classes.
- Include everything in a root `"schema"` element.
- Define a `"model"` element with the name of the exported element. For example "BillOfLading" definition when that is exported. 
- Add a  `"type": "object"`element to `schema`.
- Define a single property for the `schema` object, pointing at the root element of the schema. 
- Place all the exported classes in "/properties" (instead of /components/schemas where OpenAPI has them. Remember that all the references between classes also need to adjust to this. 

This is how the result should look: 
```
      "schema": {
        "model": "BillOfLading",
        "definitions": {
            [all definitions go here, just like for OpenAPI's /components/schemas]
        },
        "type": "object",
        "properties": {
          "billOfLading": {
            "$ref": "#/definitions/BillOfLading"
          }
        }
```

**Comment by faizanvahevaria** [comment]
Hello @nissimsan 
Please provide me example of 'layout' and 'data' object so i can move forward to generate it.
https://edi3.slack.com/files/UE1C68H50/FQGP910JE/untitled

**Comment by nissimsan** [comment]
@faizanvahevaria , the schema itself comes out correctly. I owe you more input on layout, sorry I haven't had time to work on that yet. I expect to have something for you early next week.

**Comment by faizanvahevaria** [comment]
Okey

**Comment by faizanvahevaria** [comment]
@nissimsan 
Please provide me 'layout' and 'data' part structure for JSON Schema generation and close this issue if it fine.

**Comment by nissimsan** [comment]
@faizanvahevaria, still trying to find time for the layout specification. Meanwhile, a small bug on how the json schema gets generated: 
All the classes need to be added under `/definitions`. Currently you add them all under `/properties`.
The only thing which is to be included under `/properties` is the base element (the class implementing the exported interface). 

This logic is:
All the classes are defined in `/definitions`. 
The root element is a `/property` (the only property) of the schema. 

I'm including a screenshot of how it gets exported not (left) and how it need to look (right).
![image](https://user-images.githubusercontent.com/34443212/70612505-5125c500-1c07-11ea-97d9-c4721fe8926f.png)

**Comment by faizanvahevaria** [comment]
@nissimsan 
Please close ticket this is resolved

**Comment by nissimsan** [comment]
@faizanvahevaria , I finally found time for writing a spec for the "layout" json form part of this. Sorry that it's taken me so long! Here goes... 


1. Include another selection in the exporting options: "JSON Form". JSON Forms is a kind of envelope for JSON Schema, adding layout and data elements. When exporting a JSON Form, the export should have the following structure: 
```
{
  schema{}, //This should includes exactly the content of the JSON Schema output.
  layout[], //This array is to be populated based on below rules.
  data{} //A JSON object used to exemplify the form, populated from example values (issue #44).
}
```


2. This and all subsequent rules are elements added to the `layout[]` array. For the exported root element, add this as the first element: 
```
{
  "widget": "message",
  "message": "<h1>Name Of Model</h1>" //This should be the name of the exported interface, but turned from camel casing to human readible ("BillOfLading" to "Bill Of Lading")
}
```


3. For each simple attribute insert the following element into `layout[]`: 
```
{
  "key": "nameOfAttribute"
}
```


4. For mandatory attributes include a `"required": "true"` parameter: 
```
{
  "key": "nameOfAttribute",
  "required": true
}
```


5. For arrays: 
```
{
  "key": "nameOfArray", //Note that the key should have only the name of the array and not the square brackets 
  "type": "array",
  "items": [
    {
      "key": "nameOfAttribute"
    },
    {
      "key": "nameOfNextAttribute"
    }
  ]
}
```


6. For complex types: 
```
{
  "key": "nameOfObject", //Again, this should be without the square brackets.
  "type": "section",
  "items": [
    {
      "key": "nameOfAttribute"
    }
  ]
}
```


7. For nested elements (both arrays and complex types), always just include the full path. Example: 
```
      {
        "key": "billOfLading.references",
        "type": "array",
        "items": [
          {
            "key": "billOfLading.references[].type"
          },
          {
            "key": "billOfLading.references[].value"
          }
        ]
      }
```

**Comment by faizanvahevaria** [comment]
@nissimsan I have following queries

> 3. For each simple attribute insert the following element into layout[]:
> {
>   "key": "nameOfAttribute"
> }
In above point, We have more than one properties of more than one elements. So, Properties of which element to be added in this point?

**Comment by faizanvahevaria** [comment]
@nissimsan 
I populate layout section as you wrote in the comments and as much as I understand. Please let me know if i misunderstand. Also review and answer my queries in comment.

**Comment by nissimsan** [comment]
@faizanvahevaria, cool stuff! I just tried out the latest code deploy. My comments: 

On #1, I think we should distinguish between "JSON Schema" and "JSON Form", and make them separate choices in the drop down when exporting. They both have merit individually. This is a very minor point though. 

To answer your #3 is: it should be all properties. Both those in root and those listed within complex objects (once you get to #7). You are already doing this in the root now, so I think we're fine on point #3. 

You are exporting "type" too: `"type": "Text"`. I didn't specify this. Is there a reason you have included these? (The exception is array and section, which I did specify in #6 and #7). 

To your #5, no, this has nothing to do with enums. I can see that you seem to turn enums into array - that's not right. It's just arrays which need this to be expressed. 

To #6, that's correct. This is when a class (not a simple type) is referenced within properties. 

On #7, all I mean to say here is that you should include the entire path to nested attribute names. So `billOfLading.references` (and not just `references`), in the case where references is defined within the billOfLading object.

**Comment by faizanvahevaria** [comment]
> On #1, I think we should distinguish between "JSON Schema" and "JSON Form", and make them separate choices in the drop down when exporting. They both have merit individually. This is a very minor point though.

Ok. Please discuss with @onthebreeze and let me know where to place "JSON Schema"  "JSON Form" in the menu.

> You are exporting "type" too: "type": "Text". I didn't specify this. Is there a reason you have included these? (The exception is array and section, which I did specify in #6 and #7).

I have put it from my side in the rest type. I have removed and updated it.

> To your #5, no, this has nothing to do with enums. I can see that you seem to turn enums into array - that's not right. It's just arrays which need this to be expressed.

Object should be like as mensioned 
```
{
            "key": "Country", //Country is enumeration name
            "required": true,
            "type": "array"
}
```
Right?
But my question in this point is where to put this object in 'layout' section ?
Below is my current 'layout' part

```
"layout": [
        {
            "widget": "message",
            "message": "<h1>billOfLading</h1>"
        },
        {
            "key": "negotiable",
            "required": true,
            "type": "array",
            "items": [
                {
                    "key": "DK"
                },
                {
                    "key": "SE"
                },
                {
                    "key": "NO"
                },
                {
                    "key": "US"
                }
            ]
        },
        {
            "key": "Attribute1",
            "required": true,
            "type": "section",
            "items": [
                {
                    "key": "Reference"
                }
            ]
        }
]
```

> On #7, all I mean to say here is that you should include the entire path to nested attribute names. So billOfLading.references (and not just references), in the case where references is defined within the billOfLading object.

I have not understand above yet how to generate it.

mdj file : 
[tl-docgen-model-(22112019)-new.zip](https://github.com/gs-gs/staruml-cefact/files/3988594/tl-docgen-model-.22112019.-new.zip)

Generated output file [Bill Of Lading.zip](https://github.com/gs-gs/staruml-cefact/files/3988582/Bill.Of.Lading.zip)

**Comment by faizanvahevaria** [comment]
> > On #1, I think we should distinguish between "JSON Schema" and "JSON Form", and make them separate choices in the drop down when exporting. They both have merit individually. This is a very minor point though.
> 
> Ok. Please discuss with @onthebreeze and let me know where to place "JSON Schema" "JSON Form" in the menu.
> 
> > You are exporting "type" too: "type": "Text". I didn't specify this. Is there a reason you have included these? (The exception is array and section, which I did specify in #6 and #7).
> 
> I have put it from my side in the rest type. I have removed and updated it.
> 
> > To your #5, no, this has nothing to do with enums. I can see that you seem to turn enums into array - that's not right. It's just arrays which need this to be expressed.
> 
> Object should be like as mensioned
> 
> ```
> {
>             "key": "Country", //Country is enumeration name
>             "required": true,
>             "type": "array"
> }
> ```
> 
> Right?
> But my question in this point is where to put this object in 'layout' section ?
> Below is my current 'layout' part
> 
> ```
> "layout": [
>         {
>             "widget": "message",
>             "message": "<h1>billOfLading</h1>"
>         },
>         {
>             "key": "negotiable",
>             "required": true,
>             "type": "array",
>             "items": [
>                 {
>                     "key": "DK"
>                 },
>                 {
>                     "key": "SE"
>                 },
>                 {
>                     "key": "NO"
>                 },
>                 {
>                     "key": "US"
>                 }
>             ]
>         },
>         {
>             "key": "Attribute1",
>             "required": true,
>             "type": "section",
>             "items": [
>                 {
>                     "key": "Reference"
>                 }
>             ]
>         }
> ]
> ```
> 
> > On #7, all I mean to say here is that you should include the entire path to nested attribute names. So billOfLading.references (and not just references), in the case where references is defined within the billOfLading object.
> 
> I have not understand above yet how to generate it.
> 
> mdj file : [tl-docgen-model-(22112019)-new.zip](https://github.com/gs-gs/staruml-cefact/files/3988594/tl-docgen-model-.22112019.-new.zip)
> 
> Generated output file : [Bill Of Lading.zip](https://github.com/gs-gs/staruml-cefact/files/3988582/Bill.Of.Lading.zip)
> 
> One suggestion that do not use Hash+digit in comment for example #3, #4, #5..., etc...
> because it creates link of issue ticket.

**Comment by nissimsan** [comment]
Hey Faizan,

What you export into the layout array currently seems correct but limited to only the one class being exported:  
![image](https://user-images.githubusercontent.com/34443212/71821618-dc716980-3092-11ea-9fca-2de3c49ce3be.png)

The main point missing now is extending that to include not only the attributes defined in the exported class itself, but also all the referenced classes and super-classes. In your example, it should also include for example: 
- `acceptance` (inherited from TransportDocument
- `placeOfIssuance` (relationship, also inherited from TransportDocument)

The layout array should have all the same attributes which are in the schema. So it’s really just creating the along with the schema.

Once this is understood, I think 7) makes more sense too. For some reason your example don't have a connection from TransportDocument to most of the other classes. But if you add, say, an inheritance from Consignment to TransportDocument like this: 
![image](https://user-images.githubusercontent.com/34443212/71822049-24dd5700-3094-11ea-8a49-1efb9824f3d3.png)
Then you should export for example:
- `consignmentItems.sequence` (because it is defined in a referenced class inherited from Consignment, having a composition relationship to ConsignmentItem).

**Comment by faizanvahevaria** [comment]
@nissimsan 
Can you send me this mdj file ?

**Comment by faizanvahevaria** [comment]
@nissimsan 
Please test and let me know if any issue

**Comment by nissimsan** [comment]
@faizanvahevaria , the inheritance works now - great! All the inherited attributes are shown (shown below in the blue), but I'm still missing the composition relationships to get everything included in the layout (marked in red). 

![image](https://user-images.githubusercontent.com/34443212/74723526-0776dd80-523b-11ea-8c73-c0884d9b59e1.png)

**Comment by faizanvahevaria** [comment]
Hello nis
I want to discuss about composition & aggregation relationship.
See rule : https://creately.com/blog/diagrams/class-diagram-relationships/#Composition
 or https://edi3.org/specs/edi3-uml-profile/develop/#composition-relationship
In your TL-docgen-model.mdj file, Composition relationship direction is wrong. See uploaded image 

001.png
![001](https://user-images.githubusercontent.com/15009067/74937029-46f72280-5411-11ea-9e46-08eab3099d15.png)

002.png
![002](https://user-images.githubusercontent.com/15009067/74937035-48284f80-5411-11ea-881e-f679e462ebe5.png)

**Comment by faizanvahevaria** [comment]
yet source and target of composition relationship is at wrong side in your model file.
See 001.png in that source is 'Refernece' class and target class is 'Document' and composition rule is aggregation property should be 'composite' at source (Example : end1.aggregation='composition') side and aggregation property should be 'none' at target (Example : end2.aggregation='none') side.
We can change it manually from model explorer and diamond shape will be changed as our we expect.
For example : See 002.png file i have changed property manually from model explorer
You can confirm with steven

**Comment by onthebreeze** [comment]
@nissimsan lets close this one.  

there remains the wierd issue with staruml regarding direction of association when you add an aggregation / composition directly from the tool palette. If we stick to the practice of drawing a regular association and then adding aggregation/composiiton symbol at the source then everything should work fine.
