### ISSUE TITLE
Generating classes of json-ld vocabulary

### ISSUE THREAD

**Issue by Fak3** [gs-gs/staruml-cefact#59]
This ticket describes how to populate the {# classes #} section of generic vocab template given in the #57.
{# classes #} section should be a json list. Items of this list are json objects, representing each class, and should be generated from three places: 1) for each class present in the input mdj file 2) for each property named _type_, which have allowed values given in the enumeration [I will called it _type enumeration_ below in this ticket] 3) for each possible value of type enumeration present in the the input mdj file . 

The structure of each json object is given below:
```json
{
  "@id": "%ClassName%",
  "@type": "rdfs:Class",
  "rdfs:subClassOf": ["%ParentClass1Name%", "%ParentClass2Name%"]
}
```
The rules to build such json object from a class definition are as follows:
### @id
The object MUST have "@id" key, the value should be a string:
* Case 1) If the object is generated for the class defnition, the value of @id key should be a name of the class.
* Case 2) if the object is generated for the type enumeration, then the the value of the @id key must be the name of the enumeration.
* Case 3) if the object is generated for the item of type enumeration, then the the value of the @id key must be the name of that item.

For this example [file](https://edi3.org/specs/edi3-uml-profile/develop/SampleModel.mdj), the output should contain: 
```
# 1) Classes
{@id: Voyage, ...},
{@id: Journey, ...},
...
# 2) Type enumerations
{@id: TransportEventType_Code, ..}
...
# 3) Type enumeration values
{@id: Arrival, ..},
{@id: Departure, ..},
...
```

### @type
The object MUST have "@type" key with the value "rdfs:Class". 

### subclassing
* Case 1) If the object is generated for the class definition, and it has (one or more) direct parent class in the model, then the json object should also have key "rdfs:subClassOf" with the list value. Each item in this list should be a string, corresponding to the name of the direct parent class.
* Case 2) Type enumeration cannot have parent class, it should not have "rdfs:subClassOf" key.
* Case 3) Each item in the type enumeration should have a key "rdfs:subClassOf" with the list value, with only one item - string, equal to the Type enumeration name.

For this example [file](https://edi3.org/specs/edi3-uml-profile/develop/SampleModel.mdj), the output should contain: 
```
# 1) Classes
{@id: TransportMovement, @type: "rdfs:Class"},
{@id: Voyage, @type: "rdfs:Class", "rdfs:subClassOf":[TransportMovement]},
{@id: Journey, @type: "rdfs:Class", "rdfs:subClassOf":[TransportMovement]},
...
# 2) Type enumerations
{@id: TransportEventType_Code, @type: "rdfs:Class"}
...
# 3) Type enumeration values
{@id: Arrival, @type: "rdfs:Class", "rdfs:subClassOf":[TransportEventType_Code]},
{@id: Departure, @type: "rdfs:Class", "rdfs:subClassOf":[TransportEventType_Code]},
```

**Comment by faizanvahevaria** [comment]
@Fak3 
Please close issue if it is resolved

**Comment by Fak3** [comment]
tested, works as intended
