### ISSUE TITLE
Generate query type paramters for all non-id interface attributes

### ISSUE THREAD

**Issue by kshychko** [gs-gs/staruml-cefact#6]
At the moment all the interface parameters are generated as path parameters. For example, Vessels interface has two parameters - `id` and `Status`. The following paths are generated from it:
```
/Vessels/{id}:
    get:
      tags:
        - Vessels
      description: Get single Vessel by id
      parameters:
      - description: missing description
        in: path
        name: id
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Vessel'}
          description: OK
  /Vessels/{Status}:
    get:
      tags:
        - Vessels
      description: Get single Vessel by Status
      parameters:
      - description: missing description
        in: path
        name: Status
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Vessel'}
          description: OK
```
These two paths are in conflict, as they are efficiently the same.

Instead  `Status` attribute should be represented as a query parameter:

```
  /Vessels/{id}:
    get:
      tags:
        - Vessels
      description: Get single Vessel by id
      parameters:
      - description: missing description
        in: path
        name: id
        required: true
        schema: {type: string}
      - description: missing description
        in: query
        name: Status
        required: false
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Vessel'}
          description: OK

```
The other option would be to generate a separate path like `/Vessels/getByStatus`, but I think @onthebreeze would object this. 
@Fak3 could you please provide your input on this?

**Comment by faizanvahevaria** [comment]
@kshychko  
In SampleModel.mdj file, How to identify which parameters are non-id parameter and id parameters in Vessels Interface ?

**Comment by onthebreeze** [comment]
ok I think I understand the question.  

* First, the "id" in the API path is always the id property in the UML interface.  
* Sometimes the id will have no business meaning - eg  a GUID like GET /consignments/3d11783d-b8ef-4ca5-bbca-f9629228335e
* More often, the {id} will be a number issued by the API implementer and unique within their domain - eg GET api.dhl.com/consignments/8877655 where "8877655" is a unique consignment number within DHL namespace.

In either case there is only one {id} in the path for a GET.  

In cases where a thing might have other (not necessarily unique) identifiers, then the usage would be a GET collection with URL query parameter - eg GET /vessels?Name="viking explorer".  Might return one match but maybe there are zero or two or three vessels with that name.

**Comment by onthebreeze** [comment]
I think we might be using the UML "isID" property of an attribute in a misleading way.  I't meant to indicate the attributes of the target class of an aggregation (eg vessels)  that might be useful to return in the structure of the source class (eg voyages).  The idea is that these data elements should be sufficient to know exactly which vessel is doing the voyage - without returning all the properties of the vessel in the query response about a voyage.  the UML isID is one way to tag attributes.  Another way to actually use a UML tag.  Tags are name/value pairs so we could have a tag name like "OpenAPI" (which means the open API generator should look for these tags) and a value like "query".  That would mean that the API generator should include this property as allowed GET query string parameters.  Another OpenAPI tag value might be "aggregate" - meaning include this property in the data model of the source class when generating API.  In general we can add optional richness to API generation by adding more tag values that drive specific treatment by the generator.  Thoughts?

**Comment by onthebreeze** [comment]
actually this discussion about tags should be in edi3 repo - i'll move it there
