### ISSUE TITLE
Generating properties of json-ld vocabulary

### ISSUE THREAD

**Issue by Fak3** [gs-gs/staruml-cefact#60]
This ticket describes how to populate the {# properties #} section of generic vocab template given in the #57.
{# properties #} section should be a json list. Items of this list are json objects, representing each property, and should be generated from two places: 1) All properties of classes declared in the input mdj file 2) Aggregation and composition relationships

The structure of each json object is given below:

{
  "@id": "%PropertyName%",
  "@type": "rdf:Property",
  "rdfs:domain": "%ParentClassName%",
  "rdfs:range": "%Range%",
}

The rules to build such json object from a property definition or realtionships are as follows:

### @id
The object MUST have "@id" key, the value should be a string:

* Case 1) If the object is generated for the property definition, which belongs to some class in the source uml file, the value of @id key should be composed of that class name and the property name like this: "ClassName/PropertyName".
* Case 2) if the object is generated for the composition or aggreagation relationship, then the the value of the @id key should be composed of that class name and the raltionship name like this: "ClassName/RelationshipName".

For this example [file](https://edi3.org/specs/edi3-uml-profile/develop/SampleModel.mdj), the output should contain: 
```
# 1) properties
{@id: TransportMovement/Stay, ...},
{@id: TransportMovement/Status, ...},
...
# 2) relationships
{@id: TransportMovement/UsedTransportMeans, ..},
{@id: TransportMovement/RelatedTransportRoute, ..},
{@id: TransportMovement/ActualEvent, ..},
{@id: TransportMovement/EstimatedEvent, ..},
...
```

### @type
The object MUST have "@type" key with the value "rdf:Property". 

### Domain
The object MUST have "rdfs:domain" key with the string value, equal to the class name where this property or realtionship is declared. For ex: `"rdfs:domain": "TransportMovement"`

### Range
The object MAY have "rdfs:range" key with the string value.

Case 1)  If the object is generated for the property definition, and this property has any type listed  below, it should generate the corresponding "rdfs:range" key-value pair for the json obeject.

* DateTime: `"rdfs:range": "xsd:dateTime"`
* Date: `"rdfs:range": "xsd:date"`
* Int32: `"rdfs:range": "xsd:int"`
* Int64: `"rdfs:range": "xsd:long"`
* Float: `"rdfs:range": "xsd:float"`
* Double: `"rdfs:range": "xsd:double"`
* Byte: `"rdfs:range": "xsd:byte"`

Other types currently will not have a specified range, will probably be added in the future tickets.

Case 2) if the object is generated for the composition or aggregation relationship, then the the value of the "rdfs:range" key should be a string equal to the class name of the related object, for ex: 
```
{
  "@id": "TransportMovement/UsedTransportMeans",
  "@type": "rdf:Property",
  "rdfs:domain": "TransportMovement",
  "rdfs:range": "TransportMeans"
}
```

**Comment by faizanvahevaria** [comment]
@Fak3 
We have Other types which is not spcified in this tickers like Numeric, Indicator, Number, Boolean, Password, Binary. So i put all these type in String for temporary purpose. 
For example : "rdfs:range": "string"
Is it ok?

**Comment by Fak3** [comment]
> 1 We have Other types which is not spcified in this tickers like Numeric, Indicator, Number, Boolean, Password, Binary. 

Here are few additional mappings i am certain about:
Text: "xsd:string"
Boolean: "xsd:boolean"

Others I am not sure about. @onthebreeze - can you please clarify would that be correct interpretation for these uml types? :

Numeric: "xsd:nonNegativeInteger"
Indicator: "xsd:boolean"
Number: "xsd:integer"
Password "xsd:string"

Binary: there are many possible encodings to represent a binary as a json string - will we use any particular one?

> So i put all these type in String for temporary purpose. For example : "rdfs:range": "string" Is it ok?

No, just omit "rdfs:range" property altogether.

> 2 What If property type is any reference like 'UMLClass', 'UMLInterface' or 'UMLEnumeration' ?

cc @onthebreeze. Where those types are used? Is there any example file?

> 3 What if relationship name is not given in Aggregation & Composition relationsihp ? For now i put target class name when relationship name is not given.

Hm, i think its okay for now.

**Comment by faizanvahevaria** [comment]
> cc @onthebreeze. Where those types are used? Is there any example file?
Only Enumeration is referenced in class attribute type. Example : 'TransportEvent' class has 'Type' property that its type is Enumeration 'TransportEventType_Code'

**Comment by faizanvahevaria** [comment]
> Others I am not sure about. @onthebreeze - can you please clarify would that be correct interpretation for these uml types? :

You can find datatype
https://edi3.org/specs/edi3-uml-profile/develop/#data-types

**Comment by Fak3** [comment]
> Only Enumeration is referenced in class attribute type. Example : 'TransportEvent' class has 'Type' property that its type is Enumeration 'TransportEventType_Code'

Ignore them for now. Type enumerations are already mapped to classes. We will have to see if we need any other kind of enumerations.

**Comment by Fak3** [comment]
> You can find datatype
https://edi3.org/specs/edi3-uml-profile/develop/#data-types

I opened #62 to clarify the use of compound datatypes. For now, just omit the "rdfs:range" for them.

**Comment by faizanvahevaria** [comment]
@Fak3 
Please close issue if this is fine

**Comment by faizanvahevaria** [comment]
> @Fak3
> Please close issue if this is fine

**Comment by faizanvahevaria** [comment]
Hello @Fak3 
Please close issue if this is fine

**Comment by Fak3** [comment]
> Ignore them for now. Type enumerations are already mapped to classes. We will have to see if we need any other kind of enumerations.

We now have a clear case of using non-type enumeration in Measure.UOM.

The property which a named `type` the processing already defined in the ticket #59 (_type properties_), so here I describe the processing of the _non-type properties_ - i.e. those which are NOT named `type`, and have range of Enumeration. Although i can't find a good example in our repositories. `TransportMeansPartyRole_Code` and `MovementPartyRoleCode` enumerations may not be actually used if we decide so in #56. So in this [file
](https://edi3.org/specs/edi3-uml-profile/develop/SampleModel.mdj) there is Measure.UOM property, but the file is missing the enumeration which should be named `UNECERec20_Code`
![Screenshot_20200102_134831](https://user-images.githubusercontent.com/991641/71663468-6acdae80-2d66-11ea-9e18-7fe94ee226aa.jpeg)

Anyway, plugin should process enumerations as follows:

1) Add new list to the json-ld vocabulary template (described in #57), called `rdfs_instances`:
```json
...
   "rdfs_classes": [
      {# classes #}
    ],
    "rdfs_properties": [
      {# properties #}
    ],
    // NEW
    "rdfs_instances": [
      {# instances #}
    ]
...
```

2) For each property, if it is not called `type` and its range is Enumeration:
* create new json object representing rdfs property as it already implemented
 * set the property range to the %EnumName%:
```json
{
"@id": "%PropertyName%",
"@type": "rdf:Property",
"rdfs:domain": "%ParentClassName%",
"rdfs:range": "%EnumName%",
}
```
for ex:
```json
{
"@id": "Measure.UOM",
"@type": "rdf:Property",
"rdfs:domain": "Measure",
"rdfs:range": "UNECERec20_Code",   # NEW
}
```
add this json object to the list of rdfs_preoperties (already implemented)

* create new json object representing rdfs class, with the same name as Enumeration:
```json
{
  "@id": "%EnumName%",
  "@type": "rdfs:Class",
}
```
for ex:
```json
{
  "@id": "UNECERec20_Code",
  "@type": "rdfs:Class",
}
```
add this json object to the list of rdfs_classes.

* For each value of this enumeration, create new json object representing rdfs instance, and add it to the list of rdfs_instances:
```json
"rdfs_instances": {
  {
    "@id": "%EnumName%/%value1%",
    "@type": "%EnumName%",
  },
  {
    "@id": "%EnumName%/%value2%",
    "@type": "%EnumName%",
  },
 ...
}
```
for ex this Enumeration 
![Screenshot_20200102_143432](https://user-images.githubusercontent.com/991641/71665166-de72ba00-2d6c-11ea-9b21-002f6d4153ae.jpeg)
Should produce
```json
"rdfs_instances": {
  {
    "@id": "TransportMeansPartyRole_Code/ServiceProvider",
    "@type": "TransportMeansPartyRole_Code",
  },
  {
    "@id": "TransportMeansPartyRole_Code/Owner",
    "@type": "TransportMeansPartyRole_Code",
  },
 ...
}
```

**Comment by faizanvahevaria** [comment]
@Fak3 
I have updated latest code to master. Please test JSON-LD generation with updated code and let me know if it is fine or not.

**Comment by Fak3** [comment]
There are few issues:
1) It should not generate rdfs_instance for `TransportEventType_Code`, becaues it is a _type enumeration_, i.e. used in property named `type`
2) `Measure/UOM` currently missing range:
```
              {
                "@id": "Measure/UOM",
                "@type": "rdf:Property",
                "rdfs:domain": "Measure",
                "rdfs:range": ""
            },
```
it should have `"rdfs:range": "UNECERec20_Code"`

**Comment by Fak3** [comment]
Looks good
