### ISSUE TITLE
Representation of complex uml datatypes in json and json-ld

### ISSUE THREAD

**Issue by Fak3** [gs-gs/staruml-cefact#62]
In the [uml profile doc](https://edi3.org/specs/edi3-uml-profile/develop/#core-data-types) there are few compound data types, such as `Measure`, `Identifier`, `Code` etc. Currently these are represented as plain json string in the implementation of this plugin. 

The additional data like identifier scheme or units of measure are absent in the json schema. Is that correct? Should we describe how a client should interpret the plain json string?

**Comment by Fak3** [comment]
cc @onthebreeze

**Comment by Fak3** [comment]
Especially interesting case is Measure, where using int or float instead of plain string may allow for proper comparison queries.

**Comment by faizanvahevaria** [comment]
Hello @Fak3 
This issue is to continue after @onthebreeze  answer arrive?

**Comment by Fak3** [comment]
Yes, we should discuss it first

**Comment by onthebreeze** [comment]
i think option 4 is the most aligned with UN/CEFACT code types.  Lets go with that?

**Comment by faizanvahevaria** [comment]
@onthebreeze I have a question for

> Use nested-representation of compound measure, where it becomes an object, which has at least two properties - value and unit i.e Measure becomes a class, which has value (float?) and unit (WeightUnitsEnum) properties. The example request payload then will look like a nested object for the NetWeight property:
> 
> {
>   "Identifier": "http://maersk.com/vesels/1",
>   "NetWeight": {
>      "value": 370.3,
>      "unit": "Tons",
>   }
> }

Suppose i have created a class 'Measure' and added two properties named 'value', 'unit'.
My question is that if UMLAttribute name is 'value' and type is 'float'. How i can export value of unit while generating JSON-LD ?

**Comment by Fak3** [comment]
What is `UMLAttribute`?

**Comment by Fak3** [comment]
> How i can export value of unit while generating JSON-LD like "value": 370.3,

Plugin should not generate json-ld payloads. It should only generate linked data vocabulary and in the future, json-ld context.

**Comment by faizanvahevaria** [comment]
> What is `UMLAttribute`? Can you please give more clear example where you see the problem?

![001](https://user-images.githubusercontent.com/15009067/71397705-44ac5e00-2644-11ea-92e3-a4b9eff34e3a.png)

Then, i will face the problem like this : https://github.com/gs-gs/staruml-cefact/issues/62#issuecomment-567920544

**Comment by Fak3** [comment]
In this file the property called `identifier` has type integer. That is possible. This ticket is about those properties which have compound type like `Measure` and others. If the property has a type "Measure", and there is a class "Measure" with one or more sub-properties, then this property should be represented as object with all sub-properties defined on that object.

For ex in this model: 
![Screenshot_20191225_143015](https://user-images.githubusercontent.com/991641/71444583-77795380-2723-11ea-9703-e004efa3cebd.jpeg)

The `netWeight` property which have type `Measure` should be represented in the json schema as object with just one property named `UOM` which have type `UNECERec20_Code` (enumeration)
```json
"netWeight": {
   "UOM": "C65",
}
```

**Comment by faizanvahevaria** [comment]
Ok. Let me clear with you that if i am not wrong we are talking in the sense of #60 (JSON-LD) not for OpenAPI generation. Am i right ? 
If am right. current representation of rdfs_properties from below 
![001](https://user-images.githubusercontent.com/15009067/71465160-d3a2ad00-27e1-11ea-9843-a6ba74294a65.png)

is as below...

```
"rdfs_properties": [
            {
                "@id": "TransportMovement/Identification",
                "@type": "rdf:Property",
                "rdfs:domain": "TransportMovement",
                "rdfs:range": "xsd:int"
            }
]

```
I request can you write example how json object will represent for below

![001](https://user-images.githubusercontent.com/15009067/71465290-31cf9000-27e2-11ea-9967-1ba26088cbe0.png)

**Comment by Fak3** [comment]
1) For the Measure class itself, this class and all its properties has to be added:
Class:
```
"rdfs_classes": [
            {
                "@id": "Measure",
                "@type": "rdfs:Class",
            }
]
```
properties:
```
"rdfs_properties": [
            {
                "@id": "Measure/UOM",
                "@type": "rdf:Property",
                "rdfs:domain": "Measure",
            }
]

```
2) For the property which have type Measure you should generate rdfs_properties like this
![](https://user-images.githubusercontent.com/15009067/71465290-31cf9000-27e2-11ea-9967-1ba26088cbe0.png)
```
"rdfs_properties": [
            {
                "@id": "Journey/Identifier",
                "@type": "rdf:Property",
                "rdfs:domain": "Journey",
                "rdfs:range": "Measure",
            }
]
```

**Comment by faizanvahevaria** [comment]
@Fak3 I have made changes as you mention in last comment. Please check and let me know it is fine or not.

**Comment by Fak3** [comment]
Yes, looks fine
