### ISSUE TITLE
Attributes deleted from a diagram should not get exported

### ISSUE THREAD

**Issue by nissimsan** [gs-gs/staruml-cefact#64]
StarUML 3.2.0 now supports removing individual attributes from diagrams. But in the export those attributes which are removed still get exported. Please consider this for diagram exporting, so these are not exported.

**Comment by faizanvahevaria** [comment]
@nissimsan 
Please test this ticket and close if it is working fine.

**Comment by faizanvahevaria** [comment]
@nissimsan 
Please close this issue if it is fine

**Comment by faizanvahevaria** [comment]
@nissimsan 
I am goint to close this issue. Reopen if this is not fixed.
