### ISSUE TITLE
Print a warning when generating json-ld vocabulary from the uml file with unknown types.

### ISSUE THREAD

**Issue by Fak3** [gs-gs/staruml-cefact#71]
When json-ld vocabulary is generated from the uml file, and in this file there are unknown datatypes or undefined classes/enumerations, the plugin should show a warning dialog window, listing all unknown types in the file.

#### Currently supported datatypes
Numeric: "rdfs:range": "xsd:nonNegativeInteger"
Indicator: "rdfs:range": "xsd:boolean"
Number: "rdfs:range": "xsd:integer"
Password: "rdfs:range":  "xsd:string"
DateTime: "rdfs:range": "xsd:dateTime"
Date: "rdfs:range": "xsd:date"
Int32: "rdfs:range": "xsd:int"
Int64: "rdfs:range": "xsd:long"
Float: "rdfs:range": "xsd:float"
Double: "rdfs:range": "xsd:double"
Byte: "rdfs:range": "xsd:byte"

For each type of the property which is not in the list given above there should be a class or enumeration with the corresponding name defined in the file. If there is no class or enumeration with this name, then the property and its type should be printed in the warning window.

For example in this [file
](https://edi3.org/specs/edi3-uml-profile/develop/SampleModel.mdj)
![Screenshot_20200106_182259](https://user-images.githubusercontent.com/991641/71827508-6f210100-30b1-11ea-9f5e-8e30d545fbc6.jpeg)
![Screenshot_20200106_182438](https://user-images.githubusercontent.com/991641/71827586-a8f20780-30b1-11ea-97b7-4fd135056861.jpeg)

For the UOM, MIMEType and Encoding property the warning should say:
> Warning: your vocabulary may be invalid because following properties have unknown or undefined type (range):
> Measure/UOM: UNECERec20_Code
> Binary/MIMEType: MIME_Code
> Binary/Encoding: Encoding_Code

**Comment by faizanvahevaria** [comment]
@Fak3 
We display the warning dialog then whether to stop the generation or not?

**Comment by Fak3** [comment]
don't stop, let it generate. Just show the warnings

**Comment by Fak3** [comment]
lgtm
