### ISSUE TITLE
warning about uml file with unknown types

### ISSUE THREAD

**Issue by Fak3** [gs-gs/staruml-cefact#77]
The same way as in #71, when openapi schema is generated from the uml file, and in this file there are unknown datatypes or undefined classes/enumerations, the plugin should show a warning dialog window, listing all unknown types in the file.

Json/openapi  schema currently supports following uml types:
```
          'Numeric':'number';
          'Indicator':'boolean';
          'Date':'string';
               itemsObj.format = 'date';
          'DateTime':'string';
               itemsObj.format = 'date-time';
          'Integer':'integer';
          'Int32':'integer';
               itemsObj.format = 'int32';
          'Int64':'integer';
               itemsObj.format = 'int64';
          'Number':'number';
          'Float':'number';
               itemsObj.format = 'float';
          'Double':'number';
               itemsObj.format = 'double';
          'Boolean':'boolean';
          'Password':'string';
               itemsObj.format = "password";
          'Byte':'string';
               itemsObj.format = 'byte';
          'Binary':'string';
               itemsObj.format = 'binary';
```

For ex in this model: 
![Screenshot_20191225_143015](https://user-images.githubusercontent.com/991641/71444583-77795380-2723-11ea-9703-e004efa3cebd.jpeg)

The warinig message should say:
> Warning: your json schema may be invalid because following properties have unknown or undefined type:
> Measure.UOM: UNECERec20_Code
> Binary.MIMEType: MIME_Code
> ... (other missing types)

**Comment by Fak3** [comment]
Can you please add support for `Quantity` type - it should be represented as positive integer, for ex for TransportEquipment:
```yaml
        TransportEquipment:
          type: integer
          minimum: 0
```

**Comment by Fak3** [comment]
lgtm

**Comment by Fak3** [comment]
Oh, I have not tested it thoroughly - As mentioned in this comment https://github.com/gs-gs/staruml-cefact/issues/76#issuecomment-584583533 currently the plugin stops generation if it encounters unknown type. It should not stop generation, only display a warning, and represent all unknown types as strings in the oputput file.

**Comment by faizanvahevaria** [comment]
@Fak3 
Latest code is updated please test this issue

**Comment by Fak3** [comment]
Still does not work for me - the output dir only have error.txt file

**Comment by faizanvahevaria** [comment]
@Fak3  @onthebreeze 
Latest code is updated to master branch so please test this issue and close if it work fine

**Comment by faizanvahevaria** [comment]
@onthebreeze @Fak3 
please test this issue from latest code and close if it work fine

**Comment by faizanvahevaria** [comment]
@onthebreeze & @Fak3 
This issue is resolved so i am going to close this ticket
