### ISSUE TITLE
Some deleted from diagram attributes still get exported 

### ISSUE THREAD

**Issue by nissimsan** [gs-gs/staruml-cefact#78]
As discussed on slack, some attributes deleted from diagrams still comes out in the export. 
This is your assessment of the problem: "Staruml returns multiple views of the same model element (attribute). So i use visibility conditionally for the current selected diagram."

**Comment by faizanvahevaria** [comment]
@nissimsan 
Please test and let me know if any issue

**Comment by faizanvahevaria** [comment]
@Fak3  @onthebreeze 
Latest code is updated to master branch so please test this issue and close if it work fine

**Comment by faizanvahevaria** [comment]
@nissimsan 
please test this issue from latest code and close if it work fine

**Comment by nissimsan** [comment]
Thanks Faizan!
