### ISSUE TITLE
sub-resource generation isn't right

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/staruml-cefact#9]
https://edi3.org/specs/edi3-uml-profile/master/api-sample.html is generated from the model at https://edi3.org/specs/edi3-uml-profile/master/#model

/TransportEvents is incorrectly being shown as a root resource whilst it should actually be a sub-resource like /Voyages/{id}/TransportEvents/

That's because it is the target of a composition from the parent interface.

**Comment by kshychko** [comment]
@onthebreeze, I re-generated the specification file using the latest plugin code. It now includes `/Journeys/{id}/TransportEvents` and `/Voyages/{id}/TransportEvents`, but `/TransportEvents` remains as well.

**Comment by onthebreeze** [comment]
ok that's good.  But I dont think a /TransportEvent can exist outside of the transport movement that it describes.  So the UML profile needs an addition in https://edi3.org/specs/edi3-uml-profile/master/#api-serialisation-note-9

* <<interface>> classes that represent sub-resources (because they are a target of a composition relationship from a parent <<interface>> should only exist as sub-resources.
