### ISSUE TITLE
sub-resource pattern

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/staruml-cefact#90]
sub-resource:  WHEN an ```<<interface>>``` is the TARGET of a composition relationship FROM another ```<<interface>>``` THEN it is generated as a sub-resource with a path pattern resource/{id}/sub-resource

for example, in the attached model - the "TariffLine" is not a root resource.  It only exists as a sub-resource of "ImportDeclaration" . so the path pattern would be 

/ImportDeclarations/{id}/TariffLines

![import declaration](https://user-images.githubusercontent.com/13426392/74231040-b9814780-4d19-11ea-95c5-43db9cd55a0e.png)

![swaggerui](https://user-images.githubusercontent.com/13426392/74231086-d3228f00-4d19-11ea-8da5-84abfebbd7c8.png)

**Comment by onthebreeze** [comment]
so the generated swagger should have:

* POST /ImportDeclarations
* PUT /ImportDeclarations/{id}
* GET  /ImportDeclarations
* GET  /ImportDeclarations/{id}

and

* POST /ImportDeclarations/{id}/TariffLines
* PUT /ImportDeclarations/{id}/TariffLines/{id}
* GET /ImportDeclarations/{id}/TariffLines
* GET /ImportDeclarations/{id}/TariffLines/{id}

and same for the CargoLines sub-resource.

But TariffLines and CargoLines must not exist on their own - only as sub-resource of ImportDeclarations.

**Comment by faizanvahevaria** [comment]
@onthebreeze 
in this [screenshot](https://user-images.githubusercontent.com/13426392/74231040-b9814780-4d19-11ea-95c5-43db9cd55a0e.png),
Visually it shows 'CargoLines' class is target of 'ImportDeclarations' class by composition relationship.

It a confusion of arrow direction.
When i see in modelExplorer see screenshot
![006](https://user-images.githubusercontent.com/15009067/74248332-728d5500-4d0d-11ea-80d2-087f5b206076.png)

**Comment by onthebreeze** [comment]
I reversed the arrow direction - and now I get a "missing property" error in the swagger validation

**Comment by faizanvahevaria** [comment]
Hello @onthebreeze 
(in case -  I reversed the arrow direction)
After I reversed the arrow direction, Successful openapi was generated as in [this link](https://edi3.slack.com/files/UG6LNQZ3P/FTY5TB6CF/import_declaration.json) after solving the error that caused the arrow to reverse.
Then I tested the file in swagger editor. The swagger editor was generating an error i resolved those errors ([see screenshot](https://files.slack.com/files-pri/TDWTCC83F-FTL5TT3TK/success-swagger-editor.png)). 

After doing all changes here is the final generated file : 
[import declaration.zip](https://github.com/gs-gs/staruml-cefact/files/4191881/import.declaration.zip)

So, Plese let me know that is generated file ok or not.

**Comment by onthebreeze** [comment]
tested OK

**Comment by faizanvahevaria** [comment]
@Fak3  @onthebreeze 
Latest code is updated to master branch so please test this issue and close if it work fine

**Comment by faizanvahevaria** [comment]
@onthebreeze @Fak3 
please test this issue from latest code and close if it work fine

**Comment by faizanvahevaria** [comment]
@Fak3 & @onthebreeze 
This issue is resolved so i am going to close this ticket
