### ISSUE TITLE
If Alert text is too long, it does not fit the screen

### ISSUE THREAD

**Issue by Fak3** [gs-gs/staruml-cefact#97]
Warning about unknown types sometimes may become very long, so that user can't see the buttons in the bottom of alert window, as it does not fir the screen.
![Screenshot_20200224_132316](https://user-images.githubusercontent.com/991641/75144960-2678e200-5709-11ea-82f9-5d88a3becd6f.jpeg)

Maybe there is a way to have alert window with vertical scroll and limited vertical size?

**Comment by faizanvahevaria** [comment]
@Fak3 StarUML currently doesn't allow the Scroll bar in Alert box.

We can limit the error message by setting a character limit and asking the user if they want to save the entire error message/log in a file.

Would that be a better way to go, if you say, I'll get it done.

**Comment by Fak3** [comment]
I think a better way would be to split long message in parts, and show one part after another. Let's say if it is longer than 25 lines, then split it

**Comment by faizanvahevaria** [comment]
@Fak3 
I limit the error message by setting 20 lines and if there are more lines it will be written in notlinkedtype.txt for notlinkedtype dialog and vocab.txt for vocabulary dialog.
Plesae check latest code

**Comment by faizanvahevaria** [comment]
@Fak3 
This issue is resolved so i am going to close this ticket
